spring:
  application:
    name: ubbl-query-service
  devtools:
    restart:
      enabled: true
    add-properties: true

logging:
  level:
    org.springframework.boot.autoconfigure.logging: INFO

---
spring:
  profile: dev
server:
  port: 8080
  
logging:
  level:
    org.springframework.cloud.config: DEBUG
    ubbl.query_service.web.client.DataServiceClient: DEBUG
---

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    instanceId: ${DOMAIN_NAME}
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: 443
    statusPageUrl: https://${eureka.instance.hostname}/info
    healthCheckUrl: https://${eureka.instance.hostname}/health
    homePageUrl: https://${eureka.instance.hostname}/
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI}
      
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 600000
  ConnectTimeout: 10000